app:
  build: .
  ports:
    - "3003:3000"
  links:
    - db
  environment:
    - RAILS_ENV=development

db:
  image: postgres:9.3
  ports: 
    - "5432:5432"
  environment:
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=test
